name: Build and deploy ASP.NET Core App to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  PUBLISH_DIRECTORY: './publish'
  AZURE_WEBAPP_NAME: 'projeto-do-carrinho'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: Production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore

      - name: Publish application
        run: |
          dotnet publish \
            --configuration Release \
            --output ${{ env.PUBLISH_DIRECTORY }} \
            --no-build \
            --verbosity normal

      - name: Verify publish output
        run: |
          ls -R ${{ env.PUBLISH_DIRECTORY }}
          echo "Publish contents:"
          find ${{ env.PUBLISH_DIRECTORY }} -type f

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.PUBLISH_DIRECTORY }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8C88F9949F6A4138A139902420956400 }}
