name: Build and deploy ASP app to Azure Web App - projeto-do-carrinho

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./MeassuringAppWebPage.csproj

      - name: Build
        run: dotnet build ./MeassuringAppWebPage.csproj --configuration Release --no-restore

      - name: Publish to folder
        run: dotnet publish ./MeassuringAppWebPage.csproj -c Release -o ./published --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: './published/**'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
      
      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'projeto-do-carrinho'
          package: './published'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E5E7F4CF68CA4897B0C842DCB0CE17C7 }}
